name: 'Start DynamoDB in GitHub Actions'
description: 'Starts DynamoDB Local in background as a Docker container for support with GitHub Actions'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'activity'
  color: 'blue'
